### ISSUE TITLE
Support custom headline keywords

### ISSUE THREAD

**Issue by shelverizr** [amake/org_parser#14]
```
* NEXT title
* WAITING title
* MAYBE tile
* FAILED title
```

**Comment by amake** [comment]
org_parser treats them the same way Org Mode does when you have not modified `org-todo-keywords`: namely they are treated as plain text within the headline title.

To support custom keywords the straightforward thing would be to accept the equivalent of `org-todo-keywords` as an argument to the `OrgParserDefinition` constructor. Does that work for your use case?

**Comment by shelverizr** [comment]
> org_parser treats them the same way Org Mode does when you have not modified `org-todo-keywords`: namely they are treated as plain text within the headline title.
> 
> To support custom keywords the straightforward thing would be to accept the equivalent of `org-todo-keywords` as an argument to the `OrgParserDefinition` constructor. Does that work for your use case?

Yes, that's exactly what i want.

**Comment by amake** [comment]
@shelverizr Can you check #15 to confirm that that's what you had in mind?

**Comment by shelverizr** [comment]
> @shelverizr Can you check #15 to confirm that that's what you had in mind?

@amake Not entirely, I want to switch from any keyword to any other keyword.

For example, I have two categories of tasks, to-do tasks and completed tasks, their keywords are:

To-do tasks: `TODO`, `NEXT`, `WAITING`, `MAYBE`
Completed tasks: `DONE`, `FAILED`, `SUCCESS`, `STUCK`, `SHUNT`

Sometimes I need to switch from `NEXT` to `TODO`
Sometimes I need to switch from `WAITING` to `MAYBE`
Sometimes I need to switch from `STUCK` to `NEXT`

**Comment by amake** [comment]
I'm not sure what "switching" is in the context of the parser. Are you talking about application behavior?

**Comment by shelverizr** [comment]
> I'm not sure what "switching" is in the context of the parser. Are you talking about application behavior?

Yes, switching is program behavior. Sorry, I didn't notice that I was talking about the parser settings.

**Comment by amake** [comment]
Ok then that's a much bigger task than what I've done here. The application will need

- to somehow know what keywords you want
- to supply them to the parser
- to offer a UI to switch keywords

If you're an Orgro user then Orgro only has the UI. I'll have to think about how to allow specifying the desired keywords.

**Comment by shelverizr** [comment]
> Ok then that's a much bigger task than what I've done here. The application will need
> 
> * to somehow know what keywords you want
> * to supply them to the parser
> * to offer a UI to switch keywords
> 
> If you're an Orgro user then Orgro only has the UI. I'll have to think about how to allow specifying the desired keywords.

Okay, thanks for doing this.

**Comment by amake** [comment]
I've opened a ticket for Orgro: https://github.com/amake/orgro/issues/93
