### ISSUE TITLE
Licensing for Apple AppStore

### ISSUE THREAD

**Issue by MisterY** [amake/org_parser#9]
Springing from https://github.com/amake/orgro/issues/38, could we resolve any issues which may be required for publishing the apps containing the parser into the Apple AppStore?
In my understanding, the current licensing was not appropriate for Apple AppStore (shame!) but I admit I know very little in that regard.

@amake , @vHanda

I will continue with adding support for .org files in GitJournal and using org_parser for the preview mode would make us more than half-way there.
Thanks!

**Comment by amake** [comment]
I have already announced my intent to relicense this library and org_flutter here: https://github.com/amake/orgro/issues/38#issuecomment-803687293

**Comment by MisterY** [comment]
> I have already announced my intent to relicense this library and org_flutter here: [amake/orgro#38 (comment)](https://github.com/amake/orgro/issues/38#issuecomment-803687293)

Sure, thanks for that! What are the concrete steps that need to be taken from here? I would like to start experimenting with using these libraries in GitJournal.

**Comment by amake** [comment]
I need to
- Select a license
- Change the license
- Publish a new version with the license

In the meantime, you can experiment all you want locally.

**Comment by amake** [comment]
I just released org_parser v2.1.1 and org_flutter v1.3.0 under the MIT license.
